### PR TITLE
submit #1 for review

### PR DESCRIPTION
**Pull request by willmcb94**

### CODE REVIEW

**Review by emilyb93 — CHANGES_REQUESTED** [review]
Hi Will, please be more explicit about the database names. They are fine to be in the readme for this project

**Review by emilyb93 — CHANGES_REQUESTED** [review]
The database names are the same for both .env files

**Review by emilyb93 — CHANGES_REQUESTED** [review]
Almost there, make sure you are telling the user to put the correct database names in the correct files. Currently you are saying to put the test database in the dev file and vice versa

**Review by DominicFH — APPROVED** [review]
Looks fab! 👍

**Pull request merged**
